---

repos:
  - repo: https://github.com/ambv/black
    rev: 22.10.0 # Newer versions don't support Python 3.6
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: [
          "--filter-files", # skip files that are excluded in config file
          "--profile=black",
        ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.990'  # Use the sha / tag you want to point at
    hooks:
      - id: mypy
        args: [ "arger", "tests", "--config-file=.mypy.ini" ]
        pass_filenames: false
        additional_dependencies: ["types-setuptools"]
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [ python ]
        args: [ "arger", "tests", "--rcfile=.pylint.ini" ]
