site_name: arger
site_description: Create argparser automatically from functions
site_author: Noortheen Raja

repo_url: https://github.com/jnoortheen/arger
edit_uri: https://github.com/jnoortheen/arger/edit/master/docs

theme: material

markdown_extensions:
  - codehilite:
      linenums: true
  - pymdownx.snippets:
      base_path: docs/snippets
  - pymdownx.emoji

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: false
      watch:
        - arger
