site_name: arger
site_description: Create argparser automatically from functions
site_author: Noortheen Raja

repo_url: https://github.com/jnoortheen/arger
edit_uri: https://github.com/jnoortheen/arger/edit/master/docs
site_url: https://jnoortheen.github.io/arger

strict: false
theme: material

markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - pymdownx.snippets:
      base_path: docs/snippets
  - pymdownx.emoji

plugins:
  - search
  - mknotebooks
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true
            heading_level: 4
            show_root_toc_entry: false
      watch:
        - arger
