site_name: arger
site_description: Create argparser automatically from functions
site_author: Noortheen Raja

repo_url: https://github.com/jnoortheen/arger
edit_uri: https://github.com/jnoortheen/arger/edit/master/docs

theme: readthedocs

markdown_extensions:
  - codehilite:
      linenums: true

nav:
- Home: index.md
- Advanced: advanced.md
- About:
  - Release Notes: about/changelog.md
  - Contributing: about/contributing.md
  - License: about/license.md
