name: publish

on:
  release:
    types: [created, edited]
  workflow_dispatch:
jobs:
  publish:
    name: Publish Package
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      attestations: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.11
          cache: "pip"
          cache-dependency-path: "pyproject.toml"
      - name: Build
        run: |
          pip install build
          python -m build .
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
