name: Release PR

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          release-type: python

      - name: Checkout code
        uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
            python-version: 3.11
            cache: 'pip'
            cache-dependency-path: 'pyproject.toml'
        if: ${{ steps.release.outputs.release_created }}
      - name: Build
        run: |
            pip install build
            pip install '.[doc]'
            python -m build .
        if: ${{ steps.release.outputs.release_created }}
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
            password: ${{ secrets.PYPI_TOKEN }}
        if: ${{ steps.release.outputs.release_created }}
      - name: Deploy docs
        run: mkdocs gh-deploy --force
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ steps.release.outputs.release_created }}