name: Python package

on: [push]

jobs:
#  test:
#    runs-on: ubuntu-latest
#    strategy:
#      max-parallel: 4
#      matrix:
#        python-version: [3.6, 3.7, 3.8]
#
#    steps:
#    - uses: actions/checkout@master
#    - name: 'Set up Python ${{ matrix.python-version }}'
#      uses: 'abatilo/actions-poetry@v1.5.0'
#      with:
#        python-version: '${{ matrix.python-version }}'
#        poetry_version: 1.0.5
#        args: install
#    - name: Test with tox
#      run: pip install tox-gh-actions && tox

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: abatilo/actions-poetry@v1.5.0
      with:
        python-version: 3.8
        poetry_version: 1.0.5
        args: install
    - name: Lint source files
      uses: abatilo/actions-poetry@v1.5.0
      with:
        python-version: 3.8
        poetry_version: 1.0.5
        args: run make check

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: 'Set up Python ${{ matrix.python-version }}'
      uses: 'actions/setup-python@v1'
      with:
        python-version: '${{ matrix.python-version }}'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Test with pytest
      run: poetry run pytest
